// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/download-confirm/DownloadConfirm.tsx": () => import("../components/mockups/download-confirm/DownloadConfirm.tsx"),
  "./components/mockups/download-confirm/OrbitBurst.tsx": () => import("../components/mockups/download-confirm/OrbitBurst.tsx"),
  "./components/mockups/download-confirm/SheetSlide.tsx": () => import("../components/mockups/download-confirm/SheetSlide.tsx"),
  "./components/mockups/movie-unavailable/BoldType.tsx": () => import("../components/mockups/movie-unavailable/BoldType.tsx"),
  "./components/mockups/movie-unavailable/Cinematic.tsx": () => import("../components/mockups/movie-unavailable/Cinematic.tsx"),
  "./components/mockups/movie-unavailable/MovieUnavailable.tsx": () => import("../components/mockups/movie-unavailable/MovieUnavailable.tsx"),
  "./components/mockups/offline-screen/GhostCity.tsx": () => import("../components/mockups/offline-screen/GhostCity.tsx"),
  "./components/mockups/offline-screen/OfflineScreen.tsx": () => import("../components/mockups/offline-screen/OfflineScreen.tsx"),
  "./components/mockups/offline-screen/SatelliteMinimal.tsx": () => import("../components/mockups/offline-screen/SatelliteMinimal.tsx"),
  "./components/mockups/offline-screen/VhsGlitch.tsx": () => import("../components/mockups/offline-screen/VhsGlitch.tsx")
};
